name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main


# The first job is a hello-world that checks out the code, prints a message, 
# builds a Docker image, and runs a Docker container.
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Say Hello
        run: echo "Hello, World!"

      - name: Build Docker image
        run: docker build -t hello-world-app -f docker/Dockerfile .

      - name: Run Docker container
        run: docker run hello-world-app
